### ISSUE TITLE
Stored cobblestone is deleted when mined

### ISSUE THREAD

**Issue by TheDeviantCrafter** [LexManos/CobbleForDays#24]
When a cobble gen is mined, any cobblestone stores inside is deleted. It would be nice if this would either stay in the item or drop on the floor. For performance reasons the first option might be better.

**Comment by LexManos** [comment]
No, this is a design choice. Especially for higher teir gens spawning a ton in the world would be a bad idea.
Its free cobble, who cares if some is 'lost' when you pickup the block...
