### ISSUE TITLE
game crash on 1.14.4 forge .70

### ISSUE THREAD

**Issue by 5kedone** [LexManos/CobbleForDays#3]
latest forge .70 at time of writing and only version of mod on curse 

here is pastebin https://pastebin.com/sWUyNix7

its prob me doing something wrong or a interaction between one of the 89+ mods i have running

**Comment by SDUBZ** [comment]
@LexManos i am having the same issue
Crash: http://puu.sh/ExXv1/0db5ccde49.txt
log: http://puu.sh/ExXvi/00a3fd7f94.log

tested with 
forge .70 - 68
so far all crashing
with same output

**Comment by 5kedone** [comment]
can now be closed your fix in .02 fixed the error
