### ISSUE TITLE
Allow Pickaxe to Harvest Cobblegens Faster

### ISSUE THREAD

**Issue by NielsPilgaard** [LexManos/CobbleForDays#5]
It would be nice if the cobblegens could be harvested faster with a pickaxe, as it's pretty slow at the moment.

**Comment by LexManos** [comment]
Thisis correct, it's a design choice, they you're more then welcome to use a datapack and add the tags yourself.
`data/minecraft/tags/blocks/mineable/pickaxe.json`
```
{
  "values": [
    "cobblefordays:tier_1",
    "cobblefordays:tier_2",
    "cobblefordays:tier_3",
    "cobblefordays:tier_4",
    "cobblefordays:tier_5"
  ]
}
```
