### ISSUE TITLE
1.15.2 Hangs at start up after placing Cobblegen

### ISSUE THREAD

**Issue by WilxGaming** [LexManos/CobbleForDays#7]
Minecraft Version: 1.15.2

(modded) forge-31.1.0

CobbleForDays-1.1.1.jar

I saved the game just before placing and it started no problem. Placed a Tier 1, exited the game and tried to restart. It hung at:

[Render thread/INFO]: Preparing spawn area: 0%

I had to end it with Task Manager. Reloaded the save without out it. Started no problem. Placed a Tier 2. Saved and tried to restart. Same problem.

All the other mods I picked for 1.15.2 work fine. This is the only one giving me problems.

**Comment by mithorn** [comment]
Having the same issue with the tier 3.

Minecraft Version: 1.15.2

(modded) forge-31.1.2

CobbleForDays-1.1.1.jar

**Comment by LexManos** [comment]
Unable to reproduce.
