### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sunekaer** [LexManos/CobbleForDays#9]
ServerHangWatchdog detected that a single server tick took 60.00 seconds 

https://hastebin.com/ubetufojen.rb

**Comment by LatvianModder** [comment]
https://github.com/LexManos/CobbleForDays/blob/master/src/main/java/net/minecraftforge/lex/cfd/CobbleGenTile.java#L108

Maybe `pos` is null here?

**Comment by LexManos** [comment]
https://github.com/LexManos/CobbleForDays/commit/2cb164285434db24c9436563fb6bcae36a22dfce
